import { useState } from 'react'
import { useParams, Link, useNavigate } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { reminderService } from '../../api/reminderService'
import { useI18n } from '../../i18n/I18nContext'
import { formatDate } from '@hearing-clinic/shared/src/utils/formatting'
import { ReminderStatus, ReminderType, ReminderPriority } from '@hearing-clinic/shared/src/models/reminder'
import toast from 'react-hot-toast'
import ConfirmDeleteModal from '../../components/ConfirmDeleteModal'

// Helper functions to get translated labels
const getReminderTypeLabel = (type: ReminderType, t: any): string => {
  const typeMap: Record<ReminderType, keyof typeof t.reminders> = {
    FOLLOW_UP_COUNSELING: 'typeFollowUpCounseling',
    AUDIOGRAM_DUE: 'typeAudiogramDue',
    MAINTENANCE_DUE: 'typeMaintenanceDue',
    WARRANTY_EXPIRING: 'typeWarrantyExpiring',
    POST_REPAIR_CHECK: 'typePostRepairCheck',
    POST_PURCHASE_SUPPORT: 'typePostPurchaseSupport',
    CLIENT_INACTIVE: 'typeClientInactive',
    BIRTHDAY: 'typeBirthday',
    RECOMMENDATION_FOLLOW_UP: 'typeRecommendationFollowUp',
    CUSTOM: 'typeCustom',
  }
  return t.reminders[typeMap[type]] || type
}

const getReminderPriorityLabel = (priority: ReminderPriority, t: any): string => {
  const priorityMap: Record<ReminderPriority, keyof typeof t.reminders> = {
    low: 'priorityLow',
    medium: 'priorityMedium',
    high: 'priorityHigh',
  }
  return t.reminders[priorityMap[priority]] || priority
}

export default function ReminderDetailPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { t } = useI18n()
  const queryClient = useQueryClient()
  const [deleteModalOpen, setDeleteModalOpen] = useState(false)

  const { data: reminder, isLoading } = useQuery({
    queryKey: ['reminder', id],
    queryFn: () => reminderService.getById(id!),
    enabled: !!id,
  })

  const updateStatusMutation = useMutation({
    mutationFn: async ({ id, status }: { id: string; status: ReminderStatus }) => {
      return reminderService.update(id, { status })
    },
    onSuccess: () => {
      toast.success(t.reminders.reminderUpdated)
      queryClient.invalidateQueries({ queryKey: ['reminder', id] })
      queryClient.invalidateQueries({ queryKey: ['reminders'] })
    },
    onError: (error: any) => {
      toast.error(error.message || t.reminders.reminderUpdated)
    },
  })

  const deleteMutation = useMutation({
    mutationFn: () => reminderService.delete(id!),
    onSuccess: () => {
      toast.success(t.reminders.reminderDeleted)
      queryClient.invalidateQueries({ queryKey: ['reminders'] })
      navigate('/reminders')
    },
    onError: (error: any) => {
      toast.error(error.message || t.reminders.reminderDeleted)
    },
  })

  const handleStatusChange = (newStatus: ReminderStatus) => {
    if (id) {
      updateStatusMutation.mutate({ id, status: newStatus })
    }
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-lg">{t.common.loading}</div>
      </div>
    )
  }

  if (!reminder) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <p className="text-lg text-gray-600 mb-4">{t.reminders.reminderNotFound}</p>
          <Link to="/reminders" className="btn btn-primary">
            {t.common.back}
          </Link>
        </div>
      </div>
    )
  }

  const client = reminder.get('client')
  const status = reminder.get('status') as ReminderStatus
  const type = reminder.get('type') as ReminderType
  const priority = reminder.get('priority') as ReminderPriority
  const dueAt = reminder.get('dueAt')
  const description = reminder.get('description')
  const isAutoGenerated = reminder.get('isAutoGenerated')

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link
            to="/reminders"
            className="inline-flex items-center justify-center w-10 h-10 text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </Link>
          <h1 className="text-3xl font-bold">{t.reminders.reminderDetail}</h1>
        </div>
        <div className="flex gap-2">
          {status !== 'done' && (
            <button
              onClick={() => handleStatusChange('done')}
              className="btn btn-secondary"
              disabled={updateStatusMutation.isPending}
            >
              {t.reminders.markDone}
            </button>
          )}
          <button
            onClick={() => setDeleteModalOpen(true)}
            className="btn btn-danger"
          >
            {t.common.delete}
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="bg-white rounded-2xl shadow-sm p-6 space-y-6">
        {/* Title and Status */}
        <div>
          <div className="flex items-start justify-between mb-4">
            <h2 className="text-2xl font-bold text-gray-900">{reminder.get('title')}</h2>
            <div className="flex items-center gap-2 flex-wrap">
              <span
                className={`px-3 py-1 text-sm rounded-full font-medium ${
                  status === 'done'
                    ? 'bg-secondary-100 text-secondary-800'
                    : status === 'overdue'
                    ? 'bg-danger-100 text-danger-800'
                    : 'bg-accent-100 text-accent-800'
                }`}
              >
                {t.reminders[status as keyof typeof t.reminders] || status}
              </span>
              {priority && (
                <span
                  className={`px-3 py-1 text-sm rounded-full font-medium ${
                    priority === 'high'
                      ? 'bg-red-100 text-red-800'
                      : priority === 'medium'
                      ? 'bg-yellow-100 text-yellow-800'
                      : 'bg-gray-100 text-gray-800'
                  }`}
                >
                  {getReminderPriorityLabel(priority, t)}
                </span>
              )}
              {type && (
                <span className="px-3 py-1 text-sm rounded-full font-medium bg-blue-100 text-blue-800">
                  {getReminderTypeLabel(type, t)}
                </span>
              )}
              {isAutoGenerated && (
                <span className="px-3 py-1 text-sm rounded-full font-medium bg-purple-100 text-purple-800">
                  {t.reminders.autoGenerated}
                </span>
              )}
            </div>
          </div>
        </div>

        {/* Description */}
        {description && (
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-2">{t.reminders.description}</h3>
            <p className="text-gray-600 whitespace-pre-wrap">{description}</p>
          </div>
        )}

        {/* Information Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-gray-200">
          {/* Client */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-2">{t.dashboard.client}</h3>
            {client ? (
              <Link
                to={`/clients/${client.id}`}
                className="text-primary hover:underline font-medium"
              >
                {client.get('fullName')}
              </Link>
            ) : (
              <p className="text-gray-500">{t.common.notAvailable}</p>
            )}
          </div>

          {/* Due Date */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-2">{t.dashboard.due}</h3>
            <p className="text-gray-900">{formatDate(dueAt)}</p>
          </div>

          {/* Created Date */}
          {reminder.get('createdAt') && (
            <div>
              <h3 className="text-sm font-semibold text-gray-700 mb-2">{t.reminders.createdAt}</h3>
              <p className="text-gray-600">{formatDate(reminder.get('createdAt'))}</p>
            </div>
          )}

          {/* Updated Date */}
          {reminder.get('updatedAt') && (
            <div>
              <h3 className="text-sm font-semibold text-gray-700 mb-2">{t.reminders.updatedAt}</h3>
              <p className="text-gray-600">{formatDate(reminder.get('updatedAt'))}</p>
            </div>
          )}
        </div>

        {/* Status Change Buttons */}
        {status !== 'done' && (
          <div className="pt-4 border-t border-gray-200">
            <h3 className="text-sm font-semibold text-gray-700 mb-3">{t.reminders.changeStatus}</h3>
            <div className="flex gap-2">
              {status !== 'pending' && (
                <button
                  onClick={() => handleStatusChange('pending')}
                  className="btn btn-secondary"
                  disabled={updateStatusMutation.isPending}
                >
                  {t.reminders.markAsPending}
                </button>
              )}
              {status !== 'overdue' && (
                <button
                  onClick={() => handleStatusChange('overdue')}
                  className="btn btn-secondary"
                  disabled={updateStatusMutation.isPending}
                >
                  {t.reminders.markAsOverdue}
                </button>
              )}
            </div>
          </div>
        )}
      </div>

      <ConfirmDeleteModal
        isOpen={deleteModalOpen}
        onClose={() => setDeleteModalOpen(false)}
        onConfirm={() => deleteMutation.mutate()}
        title={t.reminders.deleteReminder}
        message={t.reminders.confirmDelete}
        itemName={reminder.get('title')}
        isLoading={deleteMutation.isPending}
      />
    </div>
  )
}

