const Parse = require('parse/node');
require('dotenv').config();

// Parse Server Configuration
const APP_ID = process.env.PARSE_APP_ID || 'hearing-clinic-app-id';
const MASTER_KEY = process.env.PARSE_MASTER_KEY || 'your-master-key-change-this';
const DATABASE_URI = process.env.DATABASE_URI || 'mongodb://mongo:27017/hearing-clinic-db';
const isInsideDocker = require('fs').existsSync('/.dockerenv');
const SERVER_URL = process.env.PARSE_SERVER_URL || 
  (isInsideDocker ? 'http://localhost:1337/parse' : 'http://localhost:1338/parse');

// Initialize Parse
Parse.initialize(APP_ID);
Parse.serverURL = SERVER_URL;
Parse.masterKey = MASTER_KEY;

/**
 * Helper function to create a reminder
 */
async function createReminder(data) {
  const Reminder = Parse.Object.extend('Reminder');
  const reminder = new Reminder();
  
  reminder.set('client', data.client);
  reminder.set('title', data.title);
  if (data.description) reminder.set('description', data.description);
  reminder.set('dueAt', data.dueAt);
  reminder.set('status', data.status || 'pending');
  if (data.type) reminder.set('type', data.type);
  if (data.priority) reminder.set('priority', data.priority);
  if (data.appointmentId) reminder.set('appointmentId', data.appointmentId);
  if (data.hearingReportId) reminder.set('hearingReportId', data.hearingReportId);
  if (data.isAutoGenerated !== undefined) reminder.set('isAutoGenerated', data.isAutoGenerated);
  if (data.autoRecurring !== undefined) reminder.set('autoRecurring', data.autoRecurring);
  if (data.recurringInterval) reminder.set('recurringInterval', data.recurringInterval);
  if (data.createdBy) reminder.set('createdBy', data.createdBy);
  if (data.updatedBy) reminder.set('updatedBy', data.updatedBy);
  
  return await reminder.save(null, { useMasterKey: true });
}

/**
 * Check if reminder already exists for this appointment and type
 */
async function reminderExists(appointmentId, type) {
  const Reminder = Parse.Object.extend('Reminder');
  const query = new Parse.Query(Reminder);
  query.equalTo('appointmentId', Parse.Object.createWithoutData('Appointment', appointmentId));
  query.equalTo('type', type);
  const count = await query.count({ useMasterKey: true });
  return count > 0;
}

/**
 * Create reminders for a completed appointment
 */
async function createRemindersForAppointment(appointment, adminUser) {
  const appointmentType = appointment.get('type');
  const status = appointment.get('status');
  const appointmentDate = appointment.get('date');
  const client = appointment.get('client');
  const createdBy = appointment.get('createdBy') || adminUser;

  // Only create reminders for COMPLETED appointments
  if (status !== 'COMPLETED' || !client || !appointmentDate) {
    return [];
  }

  const reminders = [];
  const apptDate = new Date(appointmentDate);
  const clientId = typeof client === 'object' ? client.id : client;
  
  // Fetch client to get fullName
  let clientFullName = '';
  if (typeof client === 'object' && client.id) {
    try {
      await client.fetch({ useMasterKey: true });
      clientFullName = client.get('fullName') || '';
    } catch (error) {
      console.error(`Error fetching client for reminder: ${error.message}`);
    }
  }
  const clientPointer = Parse.Object.createWithoutData('Client', clientId);

  if (appointmentType === 'REPAIR') {
    // 1. Kiểm tra sau sửa (2 tuần)
    const checkupDate = new Date(apptDate);
    checkupDate.setDate(checkupDate.getDate() + 14);
    
    const checkupExists = await reminderExists(appointment.id, 'POST_REPAIR_CHECK');
    if (!checkupExists) {
      const reminder = await createReminder({
        client: clientPointer,
        title: `Kiểm tra sau sửa máy - ${clientFullName}`,
        description: 'Kiểm tra máy trợ thính sau khi sửa để đảm bảo hoạt động tốt.',
        dueAt: checkupDate,
        status: checkupDate < new Date() ? 'overdue' : 'pending',
        type: 'POST_REPAIR_CHECK',
        priority: 'medium',
        appointmentId: appointment,
        isAutoGenerated: true,
        createdBy: createdBy,
        updatedBy: createdBy,
      });
      reminders.push(reminder);
    }

    // 2. Bảo trì định kỳ (6 tháng)
    const maintenanceDate = new Date(apptDate);
    maintenanceDate.setMonth(maintenanceDate.getMonth() + 6);
    
    const maintenanceExists = await reminderExists(appointment.id, 'MAINTENANCE_DUE');
    if (!maintenanceExists) {
      const reminder = await createReminder({
        client: clientPointer,
        title: `Bảo trì định kỳ máy trợ thính - ${clientFullName}`,
        description: 'Nhắc nhở bảo trì định kỳ máy trợ thính sau 6 tháng.',
        dueAt: maintenanceDate,
        status: maintenanceDate < new Date() ? 'overdue' : 'pending',
        type: 'MAINTENANCE_DUE',
        priority: 'medium',
        appointmentId: appointment,
        isAutoGenerated: true,
        autoRecurring: true,
        recurringInterval: 180, // 6 tháng
        createdBy: createdBy,
        updatedBy: createdBy,
      });
      reminders.push(reminder);
    }

  } else if (appointmentType === 'PURCHASE') {
    // Hỗ trợ sau mua: 1 tuần, 1 tháng, 3 tháng
    const intervals = [
      { days: 7, title: 'Hỗ trợ sau mua (1 tuần)', description: 'Liên hệ khách hàng sau 1 tuần để hỗ trợ và điều chỉnh máy trợ thính.', type: 'POST_PURCHASE_SUPPORT' },
      { days: 30, title: 'Hỗ trợ sau mua (1 tháng)', description: 'Theo dõi tình trạng sử dụng máy trợ thính sau 1 tháng.', type: 'POST_PURCHASE_SUPPORT' },
      { days: 90, title: 'Hỗ trợ sau mua (3 tháng)', description: 'Đánh giá hiệu quả sử dụng máy trợ thính sau 3 tháng.', type: 'POST_PURCHASE_SUPPORT' },
    ];

    for (const interval of intervals) {
      const dueDate = new Date(apptDate);
      dueDate.setDate(dueDate.getDate() + interval.days);
      
      // Check if reminder already exists (we'll use a combination of type and days)
      const existingQuery = new Parse.Query(Parse.Object.extend('Reminder'));
      existingQuery.equalTo('appointmentId', appointment);
      existingQuery.equalTo('type', interval.type);
      existingQuery.equalTo('title', `${interval.title} - ${clientFullName}`);
      const exists = await existingQuery.count({ useMasterKey: true }) > 0;
      
      if (!exists) {
        const reminder = await createReminder({
          client: clientPointer,
          title: `${interval.title} - ${clientFullName}`,
          description: interval.description,
          dueAt: dueDate,
          status: dueDate < new Date() ? 'overdue' : 'pending',
          type: interval.type,
          priority: interval.days === 7 ? 'high' : 'medium',
          appointmentId: appointment,
          isAutoGenerated: true,
          createdBy: createdBy,
          updatedBy: createdBy,
        });
        reminders.push(reminder);
      }
    }

  } else if (appointmentType === 'AUDIOGRAM') {
    // Đo thính lực định kỳ tiếp theo (6-12 tháng)
    const hearingReport = appointment.get('hearingReport');
    let nextAudiogramDate = new Date(apptDate);
    nextAudiogramDate.setMonth(nextAudiogramDate.getMonth() + 6); // Mặc định 6 tháng
    
    // Có thể điều chỉnh dựa trên recommendations trong hearing report
    if (hearingReport) {
      try {
        await hearingReport.fetch({ useMasterKey: true });
        const recommendations = hearingReport.get('recommendations');
        if (recommendations && recommendations.toLowerCase().includes('3 tháng')) {
          nextAudiogramDate = new Date(apptDate);
          nextAudiogramDate.setMonth(nextAudiogramDate.getMonth() + 3);
        }
      } catch (error) {
        console.error('Error fetching hearing report for reminder:', error.message);
      }
    }
    
    const audiogramExists = await reminderExists(appointment.id, 'AUDIOGRAM_DUE');
    if (!audiogramExists) {
      const reminder = await createReminder({
        client: clientPointer,
        title: `Đo thính lực định kỳ tiếp theo - ${clientFullName}`,
        description: 'Nhắc nhở đo thính lực định kỳ để theo dõi tình trạng thính giác.',
        dueAt: nextAudiogramDate,
        status: nextAudiogramDate < new Date() ? 'overdue' : 'pending',
        type: 'AUDIOGRAM_DUE',
        priority: 'high',
        appointmentId: appointment,
        hearingReportId: hearingReport || undefined,
        isAutoGenerated: true,
        autoRecurring: true,
        recurringInterval: 180, // 6 tháng
        createdBy: createdBy,
        updatedBy: createdBy,
      });
      reminders.push(reminder);
    }

  } else if (appointmentType === 'COUNSELING') {
    // Tư vấn theo dõi (3-6 tháng)
    const followUpDate = new Date(apptDate);
    followUpDate.setMonth(followUpDate.getMonth() + 3); // Mặc định 3 tháng
    
    const counselingExists = await reminderExists(appointment.id, 'FOLLOW_UP_COUNSELING');
    if (!counselingExists) {
      const reminder = await createReminder({
        client: clientPointer,
        title: `Tư vấn theo dõi - ${clientFullName}`,
        description: 'Nhắc nhở tư vấn theo dõi để đánh giá tiến trình và hỗ trợ khách hàng.',
        dueAt: followUpDate,
        status: followUpDate < new Date() ? 'overdue' : 'pending',
        type: 'FOLLOW_UP_COUNSELING',
        priority: 'medium',
        appointmentId: appointment,
        isAutoGenerated: true,
        autoRecurring: true,
        recurringInterval: 90, // 3 tháng
        createdBy: createdBy,
        updatedBy: createdBy,
      });
      reminders.push(reminder);
    }
  }

  return reminders;
}

/**
 * Main seed function
 */
async function seedRemindersForSampleUsers() {
  console.log('\n🚀 Starting to seed reminders for sample users...');
  console.log(`📡 Connecting to Parse Server: ${SERVER_URL}\n`);
  
  // Get admin user
  const AdminUser = Parse.Object.extend('_User');
  const adminQuery = new Parse.Query(AdminUser);
  adminQuery.equalTo('username', 'admin');
  const adminUser = await adminQuery.first({ useMasterKey: true });
  
  if (!adminUser) {
    console.warn('⚠️  Admin user not found, reminders will be created without createdBy');
  }
  
  // Find all clients with lastName "Mẫu"
  const Client = Parse.Object.extend('Client');
  const clientQuery = new Parse.Query(Client);
  clientQuery.equalTo('lastName', 'Mẫu');
  const sampleClients = await clientQuery.find({ useMasterKey: true });
  
  if (sampleClients.length === 0) {
    console.log('⚠️  No sample clients found with lastName "Mẫu"');
    console.log('   Please run seedSampleUsers.js first to create sample clients.');
    return;
  }
  
  console.log(`✅ Found ${sampleClients.length} sample client(s)\n`);
  
  let totalReminders = 0;
  let totalAppointments = 0;
  
  // Process each sample client
  for (const client of sampleClients) {
    const clientName = client.get('fullName') || `${client.get('lastName')} ${client.get('firstName')}`;
    console.log(`📋 Processing: ${clientName}`);
    
    try {
      // Find all COMPLETED appointments for this client
      const Appointment = Parse.Object.extend('Appointment');
      const appointmentQuery = new Parse.Query(Appointment);
      appointmentQuery.equalTo('client', client);
      appointmentQuery.equalTo('status', 'COMPLETED');
      appointmentQuery.include('hearingReport');
      const appointments = await appointmentQuery.find({ useMasterKey: true });
      
      console.log(`   Found ${appointments.length} completed appointment(s)`);
      totalAppointments += appointments.length;
      
      if (appointments.length === 0) {
        console.log(`   ⏭️  No completed appointments found, skipping...\n`);
        continue;
      }
      
      // Create reminders for each appointment
      let clientReminders = 0;
      for (const appointment of appointments) {
        const reminders = await createRemindersForAppointment(appointment, adminUser);
        clientReminders += reminders.length;
        totalReminders += reminders.length;
      }
      
      console.log(`   ✅ Created ${clientReminders} reminder(s)\n`);
      
    } catch (error) {
      console.error(`   ❌ Error processing ${clientName}:`, error.message);
    }
  }
  
  // Summary
  console.log('\n' + '='.repeat(60));
  console.log('📊 SEED SUMMARY');
  console.log('='.repeat(60));
  console.log(`   ✅ Sample Clients: ${sampleClients.length}`);
  console.log(`   ✅ Processed Appointments: ${totalAppointments}`);
  console.log(`   ✅ Reminders Created: ${totalReminders}`);
  console.log('='.repeat(60));
  console.log('\n✨ Reminders seed completed successfully!\n');
}

// Run the seed function
seedRemindersForSampleUsers()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Fatal error:', error);
    console.error('Stack trace:', error.stack);
    process.exit(1);
  });

