const Parse = require('parse/node');
require('dotenv').config();

// Parse Server Configuration
const APP_ID = process.env.PARSE_APP_ID || 'hearing-clinic-app-id';
const MASTER_KEY = process.env.PARSE_MASTER_KEY || 'your-master-key-change-this';
const DATABASE_URI = process.env.DATABASE_URI || 'mongodb://mongo:27017/hearing-clinic-db';
const isInsideDocker = require('fs').existsSync('/.dockerenv');
const SERVER_URL = process.env.PARSE_SERVER_URL || 
  (isInsideDocker ? 'http://localhost:1337/parse' : 'http://localhost:1338/parse');

// Initialize Parse
Parse.initialize(APP_ID);
Parse.serverURL = SERVER_URL;
Parse.masterKey = MASTER_KEY;

/**
 * Helper function to create a reminder
 */
async function createReminder(data) {
  const Reminder = Parse.Object.extend('Reminder');
  const reminder = new Reminder();
  
  // Set client - use it directly (it should be a Parse Object already)
  if (data.client) {
    // If it's already a Parse Object, use directly; otherwise create pointer
    if (data.client instanceof Parse.Object) {
      reminder.set('client', data.client);
    } else if (typeof data.client === 'string') {
      reminder.set('client', Parse.Object.createWithoutData('Client', data.client));
    } else {
      reminder.set('client', data.client);
    }
  }
  
  reminder.set('title', data.title);
  if (data.description) reminder.set('description', data.description);
  reminder.set('dueAt', data.dueAt);
  reminder.set('status', data.status || 'pending');
  if (data.type) reminder.set('type', data.type);
  if (data.priority) reminder.set('priority', data.priority);
  
  // Handle appointmentId pointer
  if (data.appointmentId) {
    if (typeof data.appointmentId === 'object' && data.appointmentId.id) {
      reminder.set('appointmentId', Parse.Object.createWithoutData('Appointment', data.appointmentId.id));
    } else {
      reminder.set('appointmentId', data.appointmentId);
    }
  }
  
  // Handle hearingReportId pointer
  if (data.hearingReportId) {
    if (typeof data.hearingReportId === 'object' && data.hearingReportId.id) {
      reminder.set('hearingReportId', Parse.Object.createWithoutData('HearingReport', data.hearingReportId.id));
    } else {
      reminder.set('hearingReportId', data.hearingReportId);
    }
  }
  
  if (data.isAutoGenerated !== undefined) reminder.set('isAutoGenerated', data.isAutoGenerated);
  if (data.autoRecurring !== undefined) reminder.set('autoRecurring', data.autoRecurring);
  if (data.recurringInterval) reminder.set('recurringInterval', data.recurringInterval);
  
  // Handle createdBy/updatedBy pointers - only set if valid
  if (data.createdBy) {
    let userId = null;
    if (typeof data.createdBy === 'object') {
      userId = data.createdBy.id || data.createdBy.objectId || data.createdBy._id;
    } else {
      userId = data.createdBy;
    }
    if (userId) {
      reminder.set('createdBy', Parse.Object.createWithoutData('_User', userId));
    }
  }
  if (data.updatedBy) {
    let userId = null;
    if (typeof data.updatedBy === 'object') {
      userId = data.updatedBy.id || data.updatedBy.objectId || data.updatedBy._id;
    } else {
      userId = data.updatedBy;
    }
    if (userId) {
      reminder.set('updatedBy', Parse.Object.createWithoutData('_User', userId));
    }
  }
  
  return await reminder.save(null, { useMasterKey: true });
}

/**
 * Check if reminder already exists for this appointment and type
 */
async function reminderExists(appointmentId, type) {
  const Reminder = Parse.Object.extend('Reminder');
  const query = new Parse.Query(Reminder);
  query.equalTo('appointmentId', Parse.Object.createWithoutData('Appointment', appointmentId));
  query.equalTo('type', type);
  const count = await query.count({ useMasterKey: true });
  return count > 0;
}

/**
 * Create reminders for a completed appointment
 */
async function createRemindersForAppointment(appointment, adminUser) {
  const appointmentType = appointment.get('type');
  const status = appointment.get('status');
  const appointmentDate = appointment.get('date');
  const appointmentClient = appointment.get('client');
  const createdBy = appointment.get('createdBy') || adminUser;

  // Only create reminders for COMPLETED appointments
  if (status !== 'COMPLETED' || !appointmentClient || !appointmentDate) {
    return [];
  }

  const reminders = [];
  const apptDate = new Date(appointmentDate);
  
  // Get client ID and create pointer
  let clientId;
  if (typeof appointmentClient === 'object') {
    clientId = appointmentClient.id || appointmentClient.objectId || appointmentClient._id;
    if (!clientId) {
      console.error('Cannot get client ID from appointment');
      return [];
    }
  } else {
    clientId = appointmentClient;
  }
  
  if (!clientId) {
    console.error('Client ID is missing');
    return [];
  }
  
  // Fetch client to get fullName
  let clientFullName = '';
  try {
    const Client = Parse.Object.extend('Client');
    const clientObj = await (new Parse.Query(Client).get(clientId, { useMasterKey: true }));
    clientFullName = clientObj.get('fullName') || '';
  } catch (error) {
    console.error(`Error fetching client ${clientId}: ${error.message}`);
  }
  
  const clientPtr = Parse.Object.createWithoutData('Client', clientId);

  if (appointmentType === 'REPAIR') {
    // 1. Kiểm tra sau sửa (2 tuần)
    const checkupDate = new Date(apptDate);
    checkupDate.setDate(checkupDate.getDate() + 14);
    
    const checkupExists = await reminderExists(appointment.id, 'POST_REPAIR_CHECK');
    if (!checkupExists) {
      const reminder = await createReminder({
        client: client,
        title: `Kiểm tra sau sửa máy - ${clientFullName}`,
        description: 'Kiểm tra máy trợ thính sau khi sửa để đảm bảo hoạt động tốt.',
        dueAt: checkupDate,
        status: checkupDate < new Date() ? 'overdue' : 'pending',
        type: 'POST_REPAIR_CHECK',
        priority: 'medium',
        appointmentId: appointment,
        isAutoGenerated: true,
        createdBy: createdBy,
        updatedBy: createdBy,
      });
      reminders.push(reminder);
    }

    // 2. Bảo trì định kỳ (6 tháng)
    const maintenanceDate = new Date(apptDate);
    maintenanceDate.setMonth(maintenanceDate.getMonth() + 6);
    
    const maintenanceExists = await reminderExists(appointment.id, 'MAINTENANCE_DUE');
    if (!maintenanceExists) {
      const reminder = await createReminder({
        client: client,
        title: `Bảo trì định kỳ máy trợ thính - ${clientFullName}`,
        description: 'Nhắc nhở bảo trì định kỳ máy trợ thính sau 6 tháng.',
        dueAt: maintenanceDate,
        status: maintenanceDate < new Date() ? 'overdue' : 'pending',
        type: 'MAINTENANCE_DUE',
        priority: 'medium',
        appointmentId: appointment,
        isAutoGenerated: true,
        autoRecurring: true,
        recurringInterval: 180, // 6 tháng
        createdBy: createdBy,
        updatedBy: createdBy,
      });
      reminders.push(reminder);
    }

  } else if (appointmentType === 'PURCHASE') {
    // Hỗ trợ sau mua: 1 tuần, 1 tháng, 3 tháng
    const intervals = [
      { days: 7, title: 'Hỗ trợ sau mua (1 tuần)', description: 'Liên hệ khách hàng sau 1 tuần để hỗ trợ và điều chỉnh máy trợ thính.', type: 'POST_PURCHASE_SUPPORT' },
      { days: 30, title: 'Hỗ trợ sau mua (1 tháng)', description: 'Theo dõi tình trạng sử dụng máy trợ thính sau 1 tháng.', type: 'POST_PURCHASE_SUPPORT' },
      { days: 90, title: 'Hỗ trợ sau mua (3 tháng)', description: 'Đánh giá hiệu quả sử dụng máy trợ thính sau 3 tháng.', type: 'POST_PURCHASE_SUPPORT' },
    ];

    for (const interval of intervals) {
      const dueDate = new Date(apptDate);
      dueDate.setDate(dueDate.getDate() + interval.days);
      
      // Check if reminder already exists (we'll use a combination of type and days)
      const existingQuery = new Parse.Query(Parse.Object.extend('Reminder'));
      existingQuery.equalTo('appointmentId', appointment);
      existingQuery.equalTo('type', interval.type);
      existingQuery.equalTo('title', `${interval.title} - ${clientFullName}`);
      const exists = await existingQuery.count({ useMasterKey: true }) > 0;
      
      if (!exists) {
        const reminder = await createReminder({
          client: client,
          title: `${interval.title} - ${clientFullName}`,
          description: interval.description,
          dueAt: dueDate,
          status: dueDate < new Date() ? 'overdue' : 'pending',
          type: interval.type,
          priority: interval.days === 7 ? 'high' : 'medium',
          appointmentId: appointment,
          isAutoGenerated: true,
          createdBy: createdBy,
          updatedBy: createdBy,
        });
        reminders.push(reminder);
      }
    }

  } else if (appointmentType === 'AUDIOGRAM') {
    // Đo thính lực định kỳ tiếp theo (6-12 tháng)
    const hearingReport = appointment.get('hearingReport');
    let nextAudiogramDate = new Date(apptDate);
    nextAudiogramDate.setMonth(nextAudiogramDate.getMonth() + 6); // Mặc định 6 tháng
    
    // Có thể điều chỉnh dựa trên recommendations trong hearing report
    if (hearingReport) {
      try {
        await hearingReport.fetch({ useMasterKey: true });
        const recommendations = hearingReport.get('recommendations');
        if (recommendations && recommendations.toLowerCase().includes('3 tháng')) {
          nextAudiogramDate = new Date(apptDate);
          nextAudiogramDate.setMonth(nextAudiogramDate.getMonth() + 3);
        }
      } catch (error) {
        console.error('Error fetching hearing report for reminder:', error.message);
      }
    }
    
    const audiogramExists = await reminderExists(appointment.id, 'AUDIOGRAM_DUE');
    if (!audiogramExists) {
      const reminder = await createReminder({
        client: client,
        title: `Đo thính lực định kỳ tiếp theo - ${clientFullName}`,
        description: 'Nhắc nhở đo thính lực định kỳ để theo dõi tình trạng thính giác.',
        dueAt: nextAudiogramDate,
        status: nextAudiogramDate < new Date() ? 'overdue' : 'pending',
        type: 'AUDIOGRAM_DUE',
        priority: 'high',
        appointmentId: appointment,
        hearingReportId: hearingReport || undefined,
        isAutoGenerated: true,
        autoRecurring: true,
        recurringInterval: 180, // 6 tháng
        createdBy: createdBy,
        updatedBy: createdBy,
      });
      reminders.push(reminder);
    }

  } else if (appointmentType === 'COUNSELING') {
    // Tư vấn theo dõi (3-6 tháng)
    const followUpDate = new Date(apptDate);
    followUpDate.setMonth(followUpDate.getMonth() + 3); // Mặc định 3 tháng
    
    const counselingExists = await reminderExists(appointment.id, 'FOLLOW_UP_COUNSELING');
    if (!counselingExists) {
      const reminder = await createReminder({
        client: client,
        title: `Tư vấn theo dõi - ${clientFullName}`,
        description: 'Nhắc nhở tư vấn theo dõi để đánh giá tiến trình và hỗ trợ khách hàng.',
        dueAt: followUpDate,
        status: followUpDate < new Date() ? 'overdue' : 'pending',
        type: 'FOLLOW_UP_COUNSELING',
        priority: 'medium',
        appointmentId: appointment,
        isAutoGenerated: true,
        autoRecurring: true,
        recurringInterval: 90, // 3 tháng
        createdBy: createdBy,
        updatedBy: createdBy,
      });
      reminders.push(reminder);
    }
  }

  return reminders;
}

/**
 * Create comprehensive reminders for a client (all types and statuses)
 */
async function createComprehensiveReminders(client, adminUser, appointments, hearingReports) {
  const now = new Date();
  const reminders = [];
  
  // Ensure client is properly fetched and get name
  try {
    await client.fetch({ useMasterKey: true });
  } catch (error) {
    console.error(`Error fetching client: ${error.message}`);
  }
  
  const clientName = client.get('fullName') || `${client.get('lastName')} ${client.get('firstName')}`;
  
  // Use client object directly - no need to create pointer
  
  // Helper to get date with offset
  const getDate = (daysOffset) => {
    const date = new Date(now);
    date.setDate(date.getDate() + daysOffset);
    return date;
  };
  
  // 1. Skip reminders from appointments for now (they're created automatically by Cloud Functions)
  // We'll focus on creating comprehensive test reminders with all types and statuses
  
  // 2. Additional test reminders with all types and statuses
  // Helper function to check if reminder exists by title
  const reminderExistsByTitle = async (title) => {
    try {
      const Reminder = Parse.Object.extend('Reminder');
      const query = new Parse.Query(Reminder);
      query.equalTo('client', client);
      query.equalTo('title', title);
      const count = await query.count({ useMasterKey: true });
      return count > 0;
    } catch (error) {
      console.error(`Error checking reminder existence: ${error.message}`);
      return false; // If check fails, allow creation
    }
  };
  
  // Helper to create reminder only if not exists
  const createReminderIfNotExists = async (data) => {
    try {
      const exists = await reminderExistsByTitle(data.title);
      if (!exists) {
        const reminder = await createReminder(data);
        reminders.push(reminder);
        console.log(`      ✅ Created: ${data.title}`);
        return reminder;
      } else {
        console.log(`      ⏭️  Skipped (exists): ${data.title}`);
      }
      return null;
    } catch (error) {
      console.error(`      ❌ Error creating reminder "${data.title}": ${error.message}`);
      return null;
    }
  };
  
  // OVERDUE reminders (quá hạn)
  await createReminderIfNotExists({
    client: client,
    title: `[OVERDUE] Đo thính lực định kỳ - ${clientName}`,
    description: 'Reminder này đã quá hạn để test trạng thái overdue.',
    dueAt: getDate(-30),
    status: 'overdue',
    type: 'AUDIOGRAM_DUE',
    priority: 'high',
    isAutoGenerated: false,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  await createReminderIfNotExists({
    client: client,
    title: `[OVERDUE] Bảo trì định kỳ - ${clientName}`,
    description: 'Nhắc nhở bảo trì đã quá hạn 15 ngày.',
    dueAt: getDate(-15),
    status: 'overdue',
    type: 'MAINTENANCE_DUE',
    priority: 'medium',
    isAutoGenerated: true,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  // PENDING - Today (hôm nay)
  await createReminderIfNotExists({
    client: client,
    title: `[TODAY] Tư vấn theo dõi - ${clientName}`,
    description: 'Reminder đến hạn hôm nay để test hiển thị.',
    dueAt: getDate(0),
    status: 'pending',
    type: 'FOLLOW_UP_COUNSELING',
    priority: 'high',
    isAutoGenerated: false,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  // PENDING - Tomorrow (ngày mai)
  await createReminderIfNotExists({
    client: client,
    title: `[TOMORROW] Kiểm tra sau sửa - ${clientName}`,
    description: 'Kiểm tra máy trợ thính vào ngày mai.',
    dueAt: getDate(1),
    status: 'pending',
    type: 'POST_REPAIR_CHECK',
    priority: 'high',
    isAutoGenerated: true,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  // PENDING - This week (tuần này)
  await createReminderIfNotExists({
    client: client,
    title: `[THIS WEEK] Hỗ trợ sau mua (1 tuần) - ${clientName}`,
    description: 'Hỗ trợ khách hàng sau khi mua máy trợ thính.',
    dueAt: getDate(3),
    status: 'pending',
    type: 'POST_PURCHASE_SUPPORT',
    priority: 'high',
    isAutoGenerated: true,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  await createReminderIfNotExists({
    client: client,
    title: `[THIS WEEK] Bảo hành sắp hết - ${clientName}`,
    description: 'Bảo hành máy trợ thính sắp hết hạn trong 5 ngày.',
    dueAt: getDate(5),
    status: 'pending',
    type: 'WARRANTY_EXPIRING',
    priority: 'medium',
    isAutoGenerated: false,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  // PENDING - Next week (tuần sau)
  await createReminderIfNotExists({
    client: client,
    title: `[NEXT WEEK] Khách hàng lâu chưa đến - ${clientName}`,
    description: 'Khách hàng đã lâu chưa đến khám, cần liên hệ.',
    dueAt: getDate(10),
    status: 'pending',
    type: 'CLIENT_INACTIVE',
    priority: 'low',
    isAutoGenerated: true,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  // PENDING - Next month (tháng sau)
  await createReminderIfNotExists({
    client: client,
    title: `[NEXT MONTH] Đo thính lực định kỳ - ${clientName}`,
    description: 'Lịch đo thính lực định kỳ tháng sau.',
    dueAt: getDate(30),
    status: 'pending',
    type: 'AUDIOGRAM_DUE',
    priority: 'medium',
    isAutoGenerated: true,
    autoRecurring: true,
    recurringInterval: 180,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  await createReminderIfNotExists({
    client: client,
    title: `[NEXT MONTH] Sinh nhật - ${clientName}`,
    description: 'Sinh nhật khách hàng vào tháng sau.',
    dueAt: getDate(35),
    status: 'pending',
    type: 'BIRTHDAY',
    priority: 'low',
    isAutoGenerated: false,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  // DONE reminders (đã hoàn thành)
  await createReminderIfNotExists({
    client: client,
    title: `[DONE] Hỗ trợ sau mua (1 tháng) - ${clientName}`,
    description: 'Đã hoàn thành hỗ trợ sau mua 1 tháng.',
    dueAt: getDate(-60),
    status: 'done',
    type: 'POST_PURCHASE_SUPPORT',
    priority: 'medium',
    isAutoGenerated: true,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  await createReminderIfNotExists({
    client: client,
    title: `[DONE] Tư vấn theo dõi - ${clientName}`,
    description: 'Đã hoàn thành tư vấn theo dõi.',
    dueAt: getDate(-90),
    status: 'done',
    type: 'FOLLOW_UP_COUNSELING',
    priority: 'low',
    isAutoGenerated: true,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  // CUSTOM reminder
  await createReminderIfNotExists({
    client: client,
    title: `[CUSTOM] Nhắc nhở tùy chỉnh - ${clientName}`,
    description: 'Đây là reminder tùy chỉnh do nhân viên tạo.',
    dueAt: getDate(7),
    status: 'pending',
    type: 'CUSTOM',
    priority: 'medium',
    isAutoGenerated: false,
    createdBy: adminUser,
    updatedBy: adminUser,
  });
  
  // RECOMMENDATION_FOLLOW_UP
  if (hearingReports && hearingReports.length > 0) {
    const reportId = hearingReports[0].id || hearingReports[0].objectId;
    if (reportId) {
      await createReminderIfNotExists({
        client: client,
        title: `[RECOMMENDATION] Theo dõi khuyến nghị - ${clientName}`,
        description: 'Theo dõi việc thực hiện các khuyến nghị từ báo cáo thính lực.',
        dueAt: getDate(14),
        status: 'pending',
        type: 'RECOMMENDATION_FOLLOW_UP',
        priority: 'medium',
        hearingReportId: Parse.Object.createWithoutData('HearingReport', reportId),
        isAutoGenerated: false,
        createdBy: adminUser,
        updatedBy: adminUser,
      });
    }
  }
  
  return reminders;
}

/**
 * Main seed function
 */
async function seedRemindersForSampleUsers() {
  console.log('\n🚀 Starting to seed comprehensive reminders for sample users...');
  console.log(`📡 Connecting to Parse Server: ${SERVER_URL}\n`);
  
  // Get admin user
  const AdminUser = Parse.Object.extend('_User');
  const adminQuery = new Parse.Query(AdminUser);
  adminQuery.equalTo('username', 'admin');
  const adminUser = await adminQuery.first({ useMasterKey: true });
  
  if (!adminUser) {
    console.warn('⚠️  Admin user not found, reminders will be created without createdBy');
  }
  
  // Find all clients with lastName "Mẫu"
  const Client = Parse.Object.extend('Client');
  const clientQuery = new Parse.Query(Client);
  clientQuery.equalTo('lastName', 'Mẫu');
  const sampleClients = await clientQuery.find({ useMasterKey: true });
  
  if (sampleClients.length === 0) {
    console.log('⚠️  No sample clients found with lastName "Mẫu"');
    console.log('   Please run seedSampleUsers.js first to create sample clients.');
    return;
  }
  
  console.log(`✅ Found ${sampleClients.length} sample client(s)\n`);
  
  let totalReminders = 0;
  let totalAppointments = 0;
  const statusCounts = { pending: 0, overdue: 0, done: 0 };
  const typeCounts = {};
  const priorityCounts = { low: 0, medium: 0, high: 0 };
  
  // Process each sample client
  for (const client of sampleClients) {
    const clientName = client.get('fullName') || `${client.get('lastName')} ${client.get('firstName')}`;
    console.log(`📋 Processing: ${clientName}`);
    
    try {
      // Find all COMPLETED appointments for this client
      const Appointment = Parse.Object.extend('Appointment');
      const appointmentQuery = new Parse.Query(Appointment);
      appointmentQuery.equalTo('client', client);
      appointmentQuery.equalTo('status', 'COMPLETED');
      appointmentQuery.include('hearingReport');
      const appointments = await appointmentQuery.find({ useMasterKey: true });
      
      // Find hearing reports for this client
      const HearingReport = Parse.Object.extend('HearingReport');
      const reportQuery = new Parse.Query(HearingReport);
      reportQuery.equalTo('client', client);
      reportQuery.limit(5);
      const hearingReports = await reportQuery.find({ useMasterKey: true });
      
      console.log(`   Found ${appointments.length} completed appointment(s)`);
      console.log(`   Found ${hearingReports.length} hearing report(s)`);
      totalAppointments += appointments.length;
      
      // Create comprehensive reminders
      const reminders = await createComprehensiveReminders(
        client,
        adminUser,
        appointments,
        hearingReports
      );
      
      // Count statistics
      reminders.forEach(reminder => {
        const status = reminder.get('status') || 'pending';
        const type = reminder.get('type') || 'CUSTOM';
        const priority = reminder.get('priority') || 'medium';
        
        statusCounts[status] = (statusCounts[status] || 0) + 1;
        typeCounts[type] = (typeCounts[type] || 0) + 1;
        priorityCounts[priority] = (priorityCounts[priority] || 0) + 1;
      });
      
      totalReminders += reminders.length;
      console.log(`   ✅ Created ${reminders.length} reminder(s)\n`);
      
    } catch (error) {
      console.error(`   ❌ Error processing ${clientName}:`, error.message);
      console.error(error.stack);
    }
  }
  
  // Summary
  console.log('\n' + '='.repeat(60));
  console.log('📊 SEED SUMMARY');
  console.log('='.repeat(60));
  console.log(`   ✅ Sample Clients: ${sampleClients.length}`);
  console.log(`   ✅ Processed Appointments: ${totalAppointments}`);
  console.log(`   ✅ Total Reminders Created: ${totalReminders}`);
  console.log('\n   📈 By Status:');
  console.log(`      - Pending: ${statusCounts.pending || 0}`);
  console.log(`      - Overdue: ${statusCounts.overdue || 0}`);
  console.log(`      - Done: ${statusCounts.done || 0}`);
  console.log('\n   📈 By Priority:');
  console.log(`      - High: ${priorityCounts.high || 0}`);
  console.log(`      - Medium: ${priorityCounts.medium || 0}`);
  console.log(`      - Low: ${priorityCounts.low || 0}`);
  console.log('\n   📈 By Type:');
  Object.entries(typeCounts).forEach(([type, count]) => {
    console.log(`      - ${type}: ${count}`);
  });
  console.log('='.repeat(60));
  console.log('\n✨ Comprehensive reminders seed completed successfully!');
  console.log('🎯 You now have reminders with all types and statuses for testing.\n');
}

// Run the seed function
seedRemindersForSampleUsers()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Fatal error:', error);
    console.error('Stack trace:', error.stack);
    process.exit(1);
  });

