const Parse = require('parse/node');
require('dotenv').config();

// Parse Server Configuration
const APP_ID = process.env.PARSE_APP_ID || 'hearing-clinic-app-id';
const MASTER_KEY = process.env.PARSE_MASTER_KEY || 'your-master-key-change-this';
const isInsideDocker = require('fs').existsSync('/.dockerenv');
const SERVER_URL = process.env.PARSE_SERVER_URL || 
  (isInsideDocker ? 'http://localhost:1337/parse' : 'http://localhost:1338/parse');

// Initialize Parse
Parse.initialize(APP_ID);
Parse.serverURL = SERVER_URL;
Parse.masterKey = MASTER_KEY;

/**
 * Helper function to create a reminder - simple version
 */
async function createReminder(client, title, description, dueAt, status, type, priority, adminUser) {
  try {
    const Reminder = Parse.Object.extend('Reminder');
    const reminder = new Reminder();
    
    // Use client object directly (already fetched)
    reminder.set('client', client);
    reminder.set('title', title);
    if (description) reminder.set('description', description);
    reminder.set('dueAt', dueAt);
    reminder.set('status', status);
    if (type) reminder.set('type', type);
    if (priority) reminder.set('priority', priority);
    if (adminUser) {
      reminder.set('createdBy', adminUser);
      reminder.set('updatedBy', adminUser);
    }
    
    return await reminder.save(null, { useMasterKey: true });
  } catch (error) {
    console.error(`      ❌ Error creating "${title}": ${error.message}`);
    return null;
  }
}

/**
 * Check if reminder with same title exists for client
 */
async function reminderExists(client, title) {
  try {
    const Reminder = Parse.Object.extend('Reminder');
    const query = new Parse.Query(Reminder);
    query.equalTo('client', client);
    query.equalTo('title', title);
    const count = await query.count({ useMasterKey: true });
    return count > 0;
  } catch (error) {
    return false;
  }
}

/**
 * Create comprehensive test reminders for a client
 */
async function createTestRemindersForClient(client, adminUser) {
  const now = new Date();
  const clientName = client.get('fullName') || `${client.get('lastName')} ${client.get('firstName')}`;
  const reminders = [];
  
  // Helper to get date with offset
  const getDate = (daysOffset) => {
    const date = new Date(now);
    date.setDate(date.getDate() + daysOffset);
    return date;
  };
  
  // Helper to create reminder only if not exists
  const createIfNotExists = async (title, description, dueAt, status, type, priority, isAuto = false) => {
    const exists = await reminderExists(client, title);
    if (!exists) {
      const reminder = await createReminder(client, title, description, dueAt, status, type, priority, adminUser);
      if (reminder) {
        if (isAuto) reminder.set('isAutoGenerated', true);
        await reminder.save(null, { useMasterKey: true });
        reminders.push(reminder);
        console.log(`      ✅ Created: ${title}`);
        return reminder;
      }
    } else {
      console.log(`      ⏭️  Skipped (exists): ${title}`);
    }
    return null;
  };
  
  console.log(`   📝 Creating test reminders for: ${clientName}`);
  
  // OVERDUE reminders
  await createIfNotExists(
    `[OVERDUE] Đo thính lực định kỳ - ${clientName}`,
    'Reminder này đã quá hạn để test trạng thái overdue.',
    getDate(-30),
    'overdue',
    'AUDIOGRAM_DUE',
    'high',
    false
  );
  
  await createIfNotExists(
    `[OVERDUE] Bảo trì định kỳ - ${clientName}`,
    'Nhắc nhở bảo trì đã quá hạn 15 ngày.',
    getDate(-15),
    'overdue',
    'MAINTENANCE_DUE',
    'medium',
    true
  );
  
  // PENDING - Today
  await createIfNotExists(
    `[TODAY] Tư vấn theo dõi - ${clientName}`,
    'Reminder đến hạn hôm nay để test hiển thị.',
    getDate(0),
    'pending',
    'FOLLOW_UP_COUNSELING',
    'high',
    false
  );
  
  // PENDING - Tomorrow
  await createIfNotExists(
    `[TOMORROW] Kiểm tra sau sửa - ${clientName}`,
    'Kiểm tra máy trợ thính vào ngày mai.',
    getDate(1),
    'pending',
    'POST_REPAIR_CHECK',
    'high',
    true
  );
  
  // PENDING - This week
  await createIfNotExists(
    `[THIS WEEK] Hỗ trợ sau mua (1 tuần) - ${clientName}`,
    'Hỗ trợ khách hàng sau khi mua máy trợ thính.',
    getDate(3),
    'pending',
    'POST_PURCHASE_SUPPORT',
    'high',
    true
  );
  
  await createIfNotExists(
    `[THIS WEEK] Bảo hành sắp hết - ${clientName}`,
    'Bảo hành máy trợ thính sắp hết hạn trong 5 ngày.',
    getDate(5),
    'pending',
    'WARRANTY_EXPIRING',
    'medium',
    false
  );
  
  // PENDING - Next week
  await createIfNotExists(
    `[NEXT WEEK] Khách hàng lâu chưa đến - ${clientName}`,
    'Khách hàng đã lâu chưa đến khám, cần liên hệ.',
    getDate(10),
    'pending',
    'CLIENT_INACTIVE',
    'low',
    true
  );
  
  // PENDING - Next month
  await createIfNotExists(
    `[NEXT MONTH] Đo thính lực định kỳ - ${clientName}`,
    'Lịch đo thính lực định kỳ tháng sau.',
    getDate(30),
    'pending',
    'AUDIOGRAM_DUE',
    'medium',
    true
  );
  
  await createIfNotExists(
    `[NEXT MONTH] Sinh nhật - ${clientName}`,
    'Sinh nhật khách hàng vào tháng sau.',
    getDate(35),
    'pending',
    'BIRTHDAY',
    'low',
    false
  );
  
  // DONE reminders
  await createIfNotExists(
    `[DONE] Hỗ trợ sau mua (1 tháng) - ${clientName}`,
    'Đã hoàn thành hỗ trợ sau mua 1 tháng.',
    getDate(-60),
    'done',
    'POST_PURCHASE_SUPPORT',
    'medium',
    true
  );
  
  await createIfNotExists(
    `[DONE] Tư vấn theo dõi - ${clientName}`,
    'Đã hoàn thành tư vấn theo dõi.',
    getDate(-90),
    'done',
    'FOLLOW_UP_COUNSELING',
    'low',
    true
  );
  
  // CUSTOM reminder
  await createIfNotExists(
    `[CUSTOM] Nhắc nhở tùy chỉnh - ${clientName}`,
    'Đây là reminder tùy chỉnh do nhân viên tạo.',
    getDate(7),
    'pending',
    'CUSTOM',
    'medium',
    false
  );
  
  return reminders;
}

/**
 * Main seed function
 */
async function seedRemindersSimple() {
  console.log('\n🚀 Starting to seed reminders (simple version)...');
  console.log(`📡 Connecting to Parse Server: ${SERVER_URL}\n`);
  
  // Get admin user
  const AdminUser = Parse.Object.extend('_User');
  const adminQuery = new Parse.Query(AdminUser);
  adminQuery.equalTo('username', 'admin');
  const adminUser = await adminQuery.first({ useMasterKey: true });
  
  if (!adminUser) {
    console.warn('⚠️  Admin user not found, reminders will be created without createdBy');
  } else {
    console.log(`✅ Found admin user: ${adminUser.get('username')}`);
  }
  
  // Find all clients with lastName "Mẫu"
  const Client = Parse.Object.extend('Client');
  const clientQuery = new Parse.Query(Client);
  clientQuery.equalTo('lastName', 'Mẫu');
  const sampleClients = await clientQuery.find({ useMasterKey: true });
  
  if (sampleClients.length === 0) {
    console.log('⚠️  No sample clients found with lastName "Mẫu"');
    console.log('   Please run seedSampleUsers.js first to create sample clients.');
    return;
  }
  
  console.log(`✅ Found ${sampleClients.length} sample client(s)\n`);
  
  let totalReminders = 0;
  const statusCounts = { pending: 0, overdue: 0, done: 0 };
  const typeCounts = {};
  const priorityCounts = { low: 0, medium: 0, high: 0 };
  
  // Process each sample client
  for (const client of sampleClients) {
    try {
      // Ensure client is fetched
      await client.fetch({ useMasterKey: true });
      
      const reminders = await createTestRemindersForClient(client, adminUser);
      totalReminders += reminders.length;
      
      // Count statistics
      reminders.forEach(reminder => {
        const status = reminder.get('status') || 'pending';
        const type = reminder.get('type') || 'CUSTOM';
        const priority = reminder.get('priority') || 'medium';
        
        statusCounts[status] = (statusCounts[status] || 0) + 1;
        typeCounts[type] = (typeCounts[type] || 0) + 1;
        priorityCounts[priority] = (priorityCounts[priority] || 0) + 1;
      });
      
      console.log(`   ✅ Created ${reminders.length} reminder(s) for ${client.get('fullName')}\n`);
      
    } catch (error) {
      console.error(`   ❌ Error processing ${client.get('fullName')}:`, error.message);
    }
  }
  
  // Summary
  console.log('\n' + '='.repeat(60));
  console.log('📊 SEED SUMMARY');
  console.log('='.repeat(60));
  console.log(`   ✅ Sample Clients: ${sampleClients.length}`);
  console.log(`   ✅ Total Reminders Created: ${totalReminders}`);
  console.log('\n   📈 By Status:');
  console.log(`      - Pending: ${statusCounts.pending || 0}`);
  console.log(`      - Overdue: ${statusCounts.overdue || 0}`);
  console.log(`      - Done: ${statusCounts.done || 0}`);
  console.log('\n   📈 By Priority:');
  console.log(`      - High: ${priorityCounts.high || 0}`);
  console.log(`      - Medium: ${priorityCounts.medium || 0}`);
  console.log(`      - Low: ${priorityCounts.low || 0}`);
  console.log('\n   📈 By Type:');
  Object.entries(typeCounts).forEach(([type, count]) => {
    console.log(`      - ${type}: ${count}`);
  });
  console.log('='.repeat(60));
  console.log('\n✨ Reminders seed completed successfully!');
  console.log('🎯 You now have reminders with all types and statuses for testing.\n');
}

// Run the seed function
seedRemindersSimple()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Fatal error:', error);
    console.error('Stack trace:', error.stack);
    process.exit(1);
  });

