import Parse from 'parse';
import { Client } from './client';
import { Appointment } from './appointment';
import { HearingReport } from './hearingReport';

export type ReminderStatus = 'pending' | 'done' | 'overdue';

export type ReminderType = 
  | 'FOLLOW_UP_COUNSELING'      // Tư vấn theo dõi
  | 'AUDIOGRAM_DUE'              // Đo thính lực đến hạn
  | 'MAINTENANCE_DUE'            // Bảo trì đến hạn
  | 'WARRANTY_EXPIRING'          // Bảo hành sắp hết
  | 'POST_REPAIR_CHECK'          // Kiểm tra sau sửa
  | 'POST_PURCHASE_SUPPORT'      // Hỗ trợ sau mua
  | 'CLIENT_INACTIVE'            // Khách hàng lâu chưa đến
  | 'BIRTHDAY'                   // Sinh nhật
  | 'RECOMMENDATION_FOLLOW_UP'   // Theo dõi khuyến nghị
  | 'CUSTOM';                    // Tùy chỉnh

export type ReminderPriority = 'low' | 'medium' | 'high';

export interface ReminderFields {
  client: Client;
  title: string;
  description?: string;
  dueAt: Date;
  status: ReminderStatus;
  type?: ReminderType;
  priority?: ReminderPriority;
  appointmentId?: Appointment | Parse.Pointer;
  hearingReportId?: HearingReport | Parse.Pointer;
  isAutoGenerated?: boolean;
  autoRecurring?: boolean;
  recurringInterval?: number; // Số ngày lặp lại
  createdBy?: Parse.User;
  updatedBy?: Parse.User;
}

export class Reminder extends Parse.Object {
  constructor(attributes?: Partial<ReminderFields>) {
    super('Reminder', attributes);
  }

  get client(): Client {
    return this.get('client');
  }

  set client(value: Client) {
    this.set('client', value);
  }

  get title(): string {
    return this.get('title');
  }

  set title(value: string) {
    this.set('title', value);
  }

  get description(): string | undefined {
    return this.get('description');
  }

  set description(value: string | undefined) {
    this.set('description', value);
  }

  get dueAt(): Date {
    return this.get('dueAt');
  }

  set dueAt(value: Date) {
    this.set('dueAt', value);
  }

  get status(): ReminderStatus {
    return this.get('status') || 'pending';
  }

  set status(value: ReminderStatus) {
    this.set('status', value);
  }

  get createdBy(): Parse.User | undefined {
    return this.get('createdBy');
  }

  get updatedBy(): Parse.User | undefined {
    return this.get('updatedBy');
  }

  get type(): ReminderType | undefined {
    return this.get('type');
  }

  set type(value: ReminderType | undefined) {
    this.set('type', value);
  }

  get priority(): ReminderPriority | undefined {
    return this.get('priority') || 'medium';
  }

  set priority(value: ReminderPriority | undefined) {
    this.set('priority', value);
  }

  get appointmentId(): Appointment | Parse.Pointer | undefined {
    return this.get('appointmentId');
  }

  set appointmentId(value: Appointment | Parse.Pointer | undefined) {
    this.set('appointmentId', value);
  }

  get hearingReportId(): HearingReport | Parse.Pointer | undefined {
    return this.get('hearingReportId');
  }

  set hearingReportId(value: HearingReport | Parse.Pointer | undefined) {
    this.set('hearingReportId', value);
  }

  get isAutoGenerated(): boolean {
    return this.get('isAutoGenerated') || false;
  }

  set isAutoGenerated(value: boolean) {
    this.set('isAutoGenerated', value);
  }

  get autoRecurring(): boolean {
    return this.get('autoRecurring') || false;
  }

  set autoRecurring(value: boolean) {
    this.set('autoRecurring', value);
  }

  get recurringInterval(): number | undefined {
    return this.get('recurringInterval');
  }

  set recurringInterval(value: number | undefined) {
    this.set('recurringInterval', value);
  }
}

Parse.Object.registerSubclass('Reminder', Reminder);

